name:  CI/CD Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: cloner le code source 
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t basic-nodejs-s3-image .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}