name:  CI/CD Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:

  build-and-push-job:
    runs-on: ubuntu-latest
    steps:

      - name: cloner le code source 
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t basic-nodejs-s3-image .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: tag docker image
        run: docker tag basic-nodejs-s3-image  assidiwassimdev/basic-nodejs-s3-image:latest

      - name: push docker image
        run: docker push assidiwassimdev/basic-nodejs-s3-image:latest

  test-job:
    runs-on: ubuntu-latest
    needs: ["build-and-push-job"]
    steps: 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: pull docker image
        run: docker pull assidiwassimdev/basic-nodejs-s3-image:latest

      - name: run unit test
        run: docker run assidiwassimdev/basic-nodejs-s3-image:latest npm test
    



        
