name: Simple CI Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Create folder my-test-1
        run: mkdir my-test-1 

      - name: Show list of folders
        run: ls

  job-2:
    runs-on: ubuntu-latest

    steps:
      - name: Create folder my-test-2
        run: mkdir my-test-2

      - name: Show list of folders
        run: ls

  job-3:
    runs-on: ubuntu-latest

    steps:
      - name: Create folder my-test-3
        run: mkdir my-test-3

      - name: Show list of folders
        run: ls