name: Simple CI Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  log-message:
    runs-on: ubuntu-latest

    steps:

      - name: create folder my-test
        run: mkdir my-test

      - name: show list of folders
        run: ls

      - run: echo "hello" 


