name:  CI/CD Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:


  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: test
        run: ls 
