name: Simple CI Workflow

# Triggers the workflow on push events
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  log-message:
    runs-on: ubuntu-latest

    steps:
      # Print a simple log message
      - name: Print Hello World
        run: echo "Hello, World!"
